import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class DLG extends JDialog {
    private JPanel contentPane;
    private JButton BRun;
    private JTextField Edit;

    String s;
    String Path;
    int i;
    String[] u = {"Word", "Excel", "PowerPoint"};

    public DLG() {
        setContentPane(contentPane);
        setModal(true);

        Runtime rt = Runtime.getRuntime();

        BRun.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                s = Edit.getText();

                for (i = 0; i <= 2; i++)
                    if (s.equals(u[i])) break;
                if (i == 3) {
                    JOptionPane.showMessageDialog(null, "Ошибочная строка", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                Path = "C:/Program Files/Microsoft Office/root/Office16/";
                switch (i) {
                    case 0:
                        Path += "WINWORD.exe";
                        break;
                    case 1:
                        Path += "Excel.exe";
                        break;
                    case 2:
                        Path += "PowerPnt.exe";
                        break;
                }
                try {
                    rt.exec(Path);
                } catch (Exception ex) {
                }
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(10, 10, 10, 10), -1, -1));
        Edit = new JTextField();
        contentPane.add(Edit, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_SOUTHWEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        BRun = new JButton();
        BRun.setText("Открыть");
        contentPane.add(BRun, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTH, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
