import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Locale;

public class DLG extends JDialog {
    private JPanel contentPane;
    private JPopupMenu PM;
    private JMenuItem MIWord;
    private JMenuItem MIExcel;
    private JMenuItem MIPowerPnt;

    String Path;
    Runtime rt;

    public DLG() {
        setContentPane(contentPane);
        setModal(true);

        rt = Runtime.getRuntime();

        PM.add(MIWord);
        PM.add(MIExcel);
        PM.add(MIPowerPnt);

        contentPane.setComponentPopupMenu(PM);

        MIWord.setName("MIWord");
        MIExcel.setName("MIExcel");
        MIPowerPnt.setName("MIPowerPnt");

        ActionListener listener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Path = "C:/Program Files/Microsoft Office/root/Office16/";

                switch (((JMenuItem) e.getSource()).getName()) {
                    case "MIWord":
                        Path += "WINWORD.exe";
                        break;
                    case "MIExcel":
                        Path += "EXCEL.exe";
                        break;
                    case "MIPowerPnt":
                        Path += "POWERPNT.exe";
                        break;
                }
                try {
                    rt.exec(Path);
                } catch (Exception ex) {
                }
            }
        };

        MIWord.addActionListener(listener);
        MIExcel.addActionListener(listener);
        MIPowerPnt.addActionListener(listener);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(4, 1, new Insets(10, 10, 10, 10), -1, -1));
        PM = new JPopupMenu();
        contentPane.add(PM, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        MIWord = new JMenuItem();
        Font MIWordFont = this.$$$getFont$$$("Moscow Sans Regular", -1, -1, MIWord.getFont());
        if (MIWordFont != null) MIWord.setFont(MIWordFont);
        MIWord.setText("Word");
        contentPane.add(MIWord, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        MIPowerPnt = new JMenuItem();
        Font MIPowerPntFont = this.$$$getFont$$$("Moscow Sans Regular", -1, -1, MIPowerPnt.getFont());
        if (MIPowerPntFont != null) MIPowerPnt.setFont(MIPowerPntFont);
        MIPowerPnt.setText("PowerPoint");
        contentPane.add(MIPowerPnt, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        MIExcel = new JMenuItem();
        Font MIExcelFont = this.$$$getFont$$$("Moscow Sans Regular", -1, -1, MIExcel.getFont());
        if (MIExcelFont != null) MIExcel.setFont(MIExcelFont);
        MIExcel.setText("Excel");
        contentPane.add(MIExcel, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
