import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class DLG extends JDialog {
    private JPanel contentPane;
    public JMenuBar MenuBar;
    private JMenu MRun;
    private JMenuItem MIWord;
    private JMenuItem MIExcel;
    private JMenuItem MIPowerPnt;

    String Path;
    Runtime rt;

    public DLG() {
        setContentPane(contentPane);
        setModal(true);

        rt = Runtime.getRuntime();

        MRun.add(MIWord);
        MRun.add(MIExcel);
        MRun.add(MIPowerPnt);

        MenuBar.add(MRun);

        MIWord.setName("MIWord");
        MIExcel.setName("MIExcel");
        MIPowerPnt.setName("MIPowerPnt");

        ActionListener listener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Path = "C:/Program Files/Microsoft Office/root/Office16/";

                switch (((JMenuItem) e.getSource()).getName()) {
                    case "MIWord":
                        Path += "WINWORD.exe";
                        break;
                    case "MIExcel":
                        Path += "EXCEL.exe";
                        break;
                    case "MIPowerPnt":
                        Path += "POWERPNT.exe";
                        break;
                }
                try {
                    rt.exec(Path);
                } catch (Exception ex) {
                }
            }
        };

        MIWord.addActionListener(listener);
        MIExcel.addActionListener(listener);
        MIPowerPnt.addActionListener(listener);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(5, 1, new Insets(10, 10, 10, 10), -1, -1));
        MenuBar = new JMenuBar();
        contentPane.add(MenuBar, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        MRun = new JMenu();
        MRun.setHorizontalAlignment(0);
        MRun.setHorizontalTextPosition(0);
        MRun.setText("Run");
        contentPane.add(MRun, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        MIWord = new JMenuItem();
        MIWord.setHorizontalAlignment(0);
        MIWord.setHorizontalTextPosition(0);
        MIWord.setText("Word");
        contentPane.add(MIWord, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        MIExcel = new JMenuItem();
        MIExcel.setHorizontalAlignment(0);
        MIExcel.setHorizontalTextPosition(0);
        MIExcel.setText("Excel");
        contentPane.add(MIExcel, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        MIPowerPnt = new JMenuItem();
        MIPowerPnt.setHorizontalAlignment(0);
        MIPowerPnt.setHorizontalTextPosition(0);
        MIPowerPnt.setText("PowerPoint");
        contentPane.add(MIPowerPnt, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
