import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.RandomAccessFile;

public class DLG extends JDialog {
    private JPanel contentPane;
    private JButton JBGoida;
    private JTextField EFirst;
    private JTextField ESecond;

    RandomAccessFile RafFirst;

    RandomAccessFile RafSecond;

    String FileNameFirst;

    String FileNameSecond;

    byte UFirst[];

    byte USecond[];
    int i, NFirst, NSecond;

    public DLG() {
        setContentPane(contentPane);
        setModal(true);

        JBGoida.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                FileNameFirst = EFirst.getText();

                FileNameSecond = ESecond.getText();

                try {
                    RafFirst = new RandomAccessFile(FileNameFirst, "rw");

                    RafSecond = new RandomAccessFile(FileNameSecond, "rw");

                    NFirst = (int) RafFirst.length();

                    NSecond = (int) RafSecond.length();

                    if (NFirst != NSecond) {
                        JOptionPane.showMessageDialog(null, "Размеры Файлов Не Равны", "Message", JOptionPane.PLAIN_MESSAGE);

                        RafFirst.close();

                        RafSecond.close();

                        return;
                    }

                    UFirst = new byte[NFirst];

                    USecond = new byte[NSecond];

                    RafFirst.read(UFirst, 0, NFirst);

                    RafSecond.read(USecond, 0, NSecond);

                    for (i = 0; i <= NFirst - 1; i++)

                        if (UFirst[i] != USecond[i]) {
                            JOptionPane.showMessageDialog(null, "Файлы Не Равны", "Message", JOptionPane.PLAIN_MESSAGE);

                            RafFirst.close();

                            RafSecond.close();

                            return;
                        }

                    if (i == NFirst) {
                        JOptionPane.showMessageDialog(null, "Файлы Равны", "Message", JOptionPane.PLAIN_MESSAGE);

                        RafFirst.close();

                        RafSecond.close();

                        return;
                    }

                } catch (Exception exc) {
                }
            }
        });
    }

    public static void main(String[] args) {
        DLG dialog = new DLG();
        dialog.pack();
        dialog.setVisible(true);
        System.exit(0);
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 2, new Insets(10, 10, 10, 10), -1, -1));
        JBGoida = new JButton();
        JBGoida.setText("Гойда");
        JBGoida.setVerticalAlignment(0);
        contentPane.add(JBGoida, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        EFirst = new JTextField();
        contentPane.add(EFirst, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        ESecond = new JTextField();
        contentPane.add(ESecond, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
