import javax.swing.*;
import java.awt.*;

public class DLG extends JDialog {
    private JPanel contentPane;

    public DLG() {
        setContentPane(contentPane);
        setModal(true);

        startFlow();
    }

    private void startFlow() {

        Runtime rt = Runtime.getRuntime();

        int ans1 = JOptionPane.showConfirmDialog(
                this,
                "Открыть Word?",
                "Первый вопрос",
                JOptionPane.YES_NO_OPTION
        );

        if (ans1 == JOptionPane.YES_OPTION) {
            try {
                rt.exec("C:\\Program Files\\Microsoft Office\\root\\Office16\\WINWORD.EXE");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Ошибка открытия ворда");
            }
            return;
        }

        int ans2 = JOptionPane.showConfirmDialog(
                this,
                "Открыть Excel?",
                "Второй вопрос",
                JOptionPane.YES_NO_OPTION
        );

        if (ans2 == JOptionPane.YES_OPTION) {
            try {
                rt.exec("C:\\Program Files\\Microsoft Office\\root\\Office16\\EXCEL.EXE");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Ошибка открытия табличек");
            }
            return;
        }

        int ans3 = JOptionPane.showConfirmDialog(
                this,
                "Открыть PowerPoint?",
                "Третий вопрос",
                JOptionPane.YES_NO_OPTION
        );

        if (ans3 == JOptionPane.YES_OPTION) {
            try {
                rt.exec("C:\\Program Files\\Microsoft Office\\root\\Office16\\POWERPNT.EXE");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Ошибка открытия презентух");
            }
            return;
        }

        JOptionPane.showMessageDialog(this, "Итого: мы ничего не выбрали");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(10, 10, 10, 10), -1, -1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}