import javax.swing.*;
import javax.swing.border.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.awt.*;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;

public class DLG extends JDialog {
    private JPanel contentPane;
    private JList List;

    Runtime rt;
    String s[] = {"Word", "Excel", "PowerPoint"};
    String Path;
    JScrollPane sp;

    public DLG() {
        setContentPane(contentPane);
        setModal(true);

        List.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));

        sp = new JScrollPane(List, ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED, ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);

        sp.setBounds(100, 20, 100, 40);

        List.setListData(s);
        rt = Runtime.getRuntime();

        List.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                Path = "C:/Program Files/Microsoft Office/root/Office16/";

                switch (((JList) e.getSource()).getSelectedIndex()) {
                    case 0:
                        Path += "WINWORD.exe";
                        break;
                    case 1:
                        Path += "Excel.exe";
                        break;
                    case 2:
                        Path += "PowerPnt.exe";
                        break;
                }
                try {
                    rt.exec(Path);
                } catch (Exception ex) {
                }
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(10, 10, 10, 10), -1, -1));
        List = new JList();
        contentPane.add(List, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
